[package]
name = "progress"
version = "0.1.0"
authors = ["Norbert Melzer <timmelzer@gmail.com>"]

[[bin]]
name = "foo"
path = "src/foo/main.rs"

[dependencies]

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"
